# Configuration read by the forecast.py script.

# OPTIONAL.
# The machine learning algorithm to be used for forecasting.
model_path: 
# The path to the assembled data to be used for forecasting (.parquet file).
data_path: 