entities:
  # - country_code: BRN
 - country_code: MMR 
  # - country_code: LAO
  # - country_code: PHL
  # - country_code: SGP  
  #- country_code: THA
  #- country_code: VNM
  #- country_code: MYS
  #- country_code: KHM
